# Linear Regression Practice


## Pytorch Basic

In [ ]:
import torch

### Tensor
파이토치에서 사용하는 가장 기본적인 자료구조
- 다양한 수식 계산 지원
- 수학의 스칼라, 벡터, 행렬 등을 일반화한 개념

In [ ]:
x = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[[1,2], [3,4]],[[1,2], [3,4]],[[1,2], [3,4]]])

print(x)
print(x.type())
print(x.size())

# 자주 사용함.
print(x.shape)

print(x.ndimension())
print(y.ndimension())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.FloatTensor
torch.Size([3, 3])
torch.Size([3, 3])
2
3


### 텐서 모양 바꾸기
* unsqueeze(x,i): tensor x에 i번째 차원 추가
* squeeze(x): tensor x에서 크기가 1인 차원 제거
* x.view([shape]): x를 [shape]의 모양으로 변환

In [ ]:
x = torch.FloatTensor([[[1,2], [3,4]],[[1,2], [3,4]],[[1,2], [3,4]]])

print(x.shape)
print(x)

x0 = x.unsqueeze(0)
print(x0)
print(x0.shape)

x1 = x0.squeeze()
print(x1.shape)

x1.view([2, 3, 2])
x1.view([3, -1])

torch.Size([3, 2, 2])
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]])
torch.Size([1, 3, 2, 2])
torch.Size([3, 2, 2])


tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

### 행렬 연산
* randn

In [ ]:
x = torch.FloatTensor([[1,2],[3,4],[5,6]])  # 3 x 2
w = torch.randn(1,2, dtype=torch.float) # 1 x 2  ==> 2 x 1
b = torch.randn(3,1, dtype=torch.float)

print(x @ w.T + b)
# torch.mm(x, w.T)
# torch.t(w) == w.T
# x @ w.T

tensor([[ -6.1258],
        [-12.7275],
        [-17.1558]])


* Autograd: requires_grad 값이 설정된 tensor에 대해서, pytorch는 자동으로 기울기를 계산해줌.

In [ ]:
w = torch.tensor(2.0, requires_grad=True)
a = w*3
l = a**2
l.backward()
print(w.grad)

tensor(36.)


## Linear Regression with Pytorch