# Linear Regression Practice


## Pytorch Basic

In [ ]:
import torch

### Tensor
파이토치에서 사용하는 가장 기본적인 자료구조
- 다양한 수식 계산 지원
- 수학의 스칼라, 벡터, 행렬 등을 일반화한 개념

In [ ]:
x = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[[1,2], [3,4]],[[1,2], [3,4]],[[1,2], [3,4]]])

print(x)
print(x.type())
print(x.size())

# 자주 사용함.
print(x.shape)

print(x.ndimension())
print(y.ndimension())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.FloatTensor
torch.Size([3, 3])
torch.Size([3, 3])
2
3


### 텐서 모양 바꾸기
* unsqueeze(x,i): tensor x에 i번째 차원 추가
* squeeze(x): tensor x에서 크기가 1인 차원 제거
* x.view([shape]): x를 [shape]의 모양으로 변환

In [ ]:
x = torch.FloatTensor([[[1,2], [3,4]],[[1,2], [3,4]],[[1,2], [3,4]]])

print(x.shape)
print(x)

x0 = x.unsqueeze(0)
print(x0)
print(x0.shape)

x1 = x0.squeeze()
print(x1.shape)

x1.view([2, 3, 2])
x1.view([3, -1])

torch.Size([3, 2, 2])
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]])
torch.Size([1, 3, 2, 2])
torch.Size([3, 2, 2])


tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

### 행렬 연산
* randn

In [ ]:
x = torch.FloatTensor([[1,2],[3,4],[5,6]])  # 3 x 2
w = torch.randn(1,2, dtype=torch.float) # 1 x 2  ==> 2 x 1
b = torch.randn(3,1, dtype=torch.float)

print(x @ w.T + b)
# torch.mm(x, w.T)
# torch.t(w) == w.T
# x @ w.T

tensor([[ -6.1258],
        [-12.7275],
        [-17.1558]])


* Autograd: requires_grad 값이 설정된 tensor에 대해서, pytorch는 자동으로 기울기를 계산해줌.

In [ ]:
w = torch.tensor(2.0, requires_grad=True)
a = w*3
l = a**2
l.backward()
print(w.grad)

tensor(36.)


## Linear Regression with Pytorch

In [45]:
import torch

x_train = torch.FloatTensor([[1,2], [3,2], [3,7], [1,1], [1,0]])
y_train = torch.FloatTensor([[4], [8], [23], [1], [-2]])
 # 원래 함수: y = 2x1 + 3x2 - 4

w = torch.randn(2,1)
b = torch.randn(1)
lr = 0.01

 # w, b값 찾기
for epoch in range(3000):
  w.requires_grad_(True)
  b.requires_grad_(True)

  h = x_train @ w + b
  cost = ((h-y_train)**2).mean()

  cost.backward()

 # 경사하강법(미분X)
  with torch.no_grad():
    w = w - lr * w.grad
    b = b - lr * b.grad

    if epoch % 100 == 0:
      print(epoch, cost.item(), w.squeeze(), b)


 # 예측하기
x_test = torch.FloatTensor([[5,10]])
y_test = x_test @ w + b
print(y_test)

0 121.1106185913086 tensor([-0.1512,  0.6793]) tensor([2.0272])
100 3.213176727294922 tensor([-0.0299,  3.2531]) tensor([-0.1889])
200 1.601880431175232 tensor([0.4186, 3.2733]) tensor([-1.3551])
300 0.8226024508476257 tensor([0.8521, 3.2063]) tensor([-2.1138])
400 0.4227420687675476 tensor([1.1754, 3.1491]) tensor([-2.6489])
500 0.2172553539276123 tensor([1.4087, 3.1070]) tensor([-3.0316])
600 0.11165167391300201 tensor([1.5761, 3.0767]) tensor([-3.3058])
700 0.05737997964024544 tensor([1.6961, 3.0550]) tensor([-3.5023])
800 0.02948862873017788 tensor([1.7821, 3.0394]) tensor([-3.6432])
900 0.015154831111431122 tensor([1.8438, 3.0283]) tensor([-3.7442])
1000 0.007788443472236395 tensor([1.8880, 3.0203]) tensor([-3.8166])
1100 0.004002577159553766 tensor([1.9197, 3.0145]) tensor([-3.8686])
1200 0.002057002391666174 tensor([1.9425, 3.0104]) tensor([-3.9058])
1300 0.001057128538377583 tensor([1.9588, 3.0075]) tensor([-3.9324])
1400 0.0005432724137790501 tensor([1.9704, 3.0054]) tensor([-

## Linear Regression with Scikit-learn

### Python의 대표 머신러닝 라이브러리

In [52]:
from sklearn.linear_model import LinearRegression

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

lr = LinearRegression()
lr.fit(x, y)

print(lr.coef_, lr.intercept_)

x_test = [[5,10]]

y_test = lr.predict(x_test)
print("===== 결과 =====")
print(y_test)

[[2. 3.]] [-4.]
===== 결과 =====
[[36.]]
