<a href="https://colab.research.google.com/github/clustering-jun/KMU-Data_Science/blob/main/L03_Softmax_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Softmax Regression Practice**


## **Softmax Regression Practice with Pytorch**

In [ ]:
import torch

x_train = torch.tensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ], dtype=torch.float )
y_train = torch.tensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0] ], dtype=torch.float )

In [ ]:
W = torch.randn(4,3, requires_grad=True) # 차원 4,3 --> raw: x_train의 차원과 동일하게, column: 맞출려고 하는 calss의 수
b = torch.randn(1,3, requires_grad=True)

optim = torch.optim.Adam([W,b], lr = 0.1)

for epoch in range(3001):

    h = torch.softmax(torch.mm(x_train, W) + b, dim = 1)
    # h = (torch.mm(x_train, W) + b).softmax(dim=1)

    cost = -torch.mean(torch.sum(y_train * torch.log(h), dim = 1))
    # cost = -(y_train * torch.log(h)).sum(dim=1).mean()

    optim.zero_grad()
    cost.backward()
    optim.step()

    with torch.no_grad():
        if epoch % 100 == 0:
            print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 3.782303810119629
epoch: 100, cost: 0.3121398389339447
epoch: 200, cost: 0.21394389867782593
epoch: 300, cost: 0.15235701203346252
epoch: 400, cost: 0.11364435404539108
epoch: 500, cost: 0.08802750706672668
epoch: 600, cost: 0.07018798589706421
epoch: 700, cost: 0.05724438652396202
epoch: 800, cost: 0.0475451685488224
epoch: 900, cost: 0.04008587449789047
epoch: 1000, cost: 0.03422482684254646
epoch: 1100, cost: 0.02953549101948738
epoch: 1200, cost: 0.025724584236741066
epoch: 1300, cost: 0.022585436701774597
epoch: 1400, cost: 0.019968602806329727
epoch: 1500, cost: 0.017764169722795486
epoch: 1600, cost: 0.015889707952737808
epoch: 1700, cost: 0.014282330870628357
epoch: 1800, cost: 0.012893588282167912
epoch: 1900, cost: 0.011685457080602646
epoch: 2000, cost: 0.010628020390868187
epoch: 2100, cost: 0.009697186760604382
epoch: 2200, cost: 0.008873621001839638
epoch: 2300, cost: 0.008141551166772842
epoch: 2400, cost: 0.0074879443272948265
epoch: 2500, cost: 0.006902

In [ ]:
# 예측하기
x_test = torch.tensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]], dtype=torch.float)

h_test = torch.softmax(torch.mm(x_test, W) + b, dim = 1)
print(h_test)
print(torch.argmax(h_test, dim = 1))

tensor([[1.0000e+00, 6.6823e-17, 1.8649e-34],
        [8.3073e-03, 7.4698e-01, 2.4471e-01],
        [2.3333e-30, 6.5070e-11, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
tensor([0, 1, 2])


## **조금 더 깔끔하게 Softmax**

### **마음에 안드는 부분**
- `[1,0,0], [0,1,0], [0,0,1]` 대신 `0, 1, 2`를 쓰면 안되나?
- 이렇게 복잡한 함수(h, cost)를 항상 직접 구현해야되나? 어차피 softmax, cross entropy인데?

In [ ]:
import torch
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.tensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ], dtype=torch.float )
y_train = torch.tensor([2,2,2,1,1,1,0,0], dtype=torch.long)

model = nn.Linear(4,3)
optim = torch.optim.Adam(model.parameters(), lr = 0.1)


for epoch in range(3001):

    h = model(x_train)
    cost = F.cross_entropy(h, y_train)

    optim.zero_grad()
    cost.backward()
    optim.step()

    with torch.no_grad():
        if epoch % 100 == 0:
            print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 2.5144050121307373
epoch: 100, cost: 0.33555638790130615
epoch: 200, cost: 0.2193930745124817
epoch: 300, cost: 0.15191562473773956
epoch: 400, cost: 0.11152353137731552
epoch: 500, cost: 0.08549431711435318
epoch: 600, cost: 0.06764886528253555
epoch: 700, cost: 0.054840922355651855
epoch: 800, cost: 0.04532477259635925
epoch: 900, cost: 0.03805794566869736
epoch: 1000, cost: 0.032382652163505554
epoch: 1100, cost: 0.027865376323461533
epoch: 1200, cost: 0.024210859090089798
epoch: 1300, cost: 0.021212300285696983
epoch: 1400, cost: 0.018721112981438637
epoch: 1500, cost: 0.016628796234726906
epoch: 1600, cost: 0.014854260720312595
epoch: 1700, cost: 0.013336055912077427
epoch: 1800, cost: 0.01202701497823
epoch: 1900, cost: 0.010890303179621696
epoch: 2000, cost: 0.00989691074937582
epoch: 2100, cost: 0.009023749269545078
epoch: 2200, cost: 0.008252129890024662
epoch: 2300, cost: 0.0075670769438147545
epoch: 2400, cost: 0.0069560641422867775
epoch: 2500, cost: 0.00640

- **주의! F.cross_entropy는 softmax와 cross entropy를 합친 것.**

In [ ]:
model

Linear(in_features=4, out_features=3, bias=True)

In [ ]:
model.parameters()

<generator object Module.parameters at 0x799f75b8b680>

In [ ]:
for a in model.parameters():
    print(a)

Parameter containing:
tensor([[-12.2440,  -0.3130,   8.2319,  -1.9318],
        [  7.2206,   0.3162,  -3.9238,   1.8617],
        [  8.8315,   0.6994,  -9.8449,   0.5202]], requires_grad=True)
Parameter containing:
tensor([-19.6614,   2.9228,  26.5391], requires_grad=True)


## **Softmax Regression with Scikit-learn**
- sklearn에는 LogisticRegression에 Softmax regressin이 함께 구현됨.
--> y에 두 종류 이상의 값이 있을 경우 softmax regression 실행

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression


x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])

# y에 0, 1 ,2 등 둘 이상의 class가 존재 --> softmax regression
y_train = np.array([2,2,2,1,1,1,0,0])

model = LogisticRegression(penalty=None)

model.fit(x_train, y_train)

# w와 b에 해당하는 값 출력
print(model.coef_, model.intercept_)

[[-59.67522386  -5.71584024  19.19765337   7.46552972]
 [ 10.79175325  -4.89176604  -0.41108063  11.03996337]
 [ 48.88347062  10.60760628 -18.78657274 -18.5054931 ]] [-27.82443948 -15.01027699  42.83471647]


In [ ]:
# 예측하기
x_test = np.array([[1,11,10,9], [1,3,4,3], [1,1,0,1]])

print(model.predict(x_test))

[0 1 2]
